Toggled on test mode, switched to PEST from PHPUnits

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,6 +50,10 @@ jobs:
         working-directory: src
         run: php artisan migrate
 
-      - name: Run tests (ignore failures)
+      - name: Run tests (if failures occur, check the database service logs for details)
         working-directory: src
-        run: php artisan test || true
+        run: php artisan test
+        
+      # - name: Run tests (ignore failures)
+      #   working-directory: src
+      #   run: php artisan test || true
